### ISSUE TITLE
与AcrylicDnsProxy+DnsChooser相比

### ISSUE THREAD

**Issue by ntm25576** [miaomiaosoft/DnsForwarderGUI#1]
优缺点

**Comment by miaomiaosoft** [comment]
目前在用DnsForwarder+DnsChooser组合，前两天也和DnsForwarder作者提出建议能不能增加与DnsChooser类似的功能，不过看作者意思可能不行。

与AcrylicDnsProxy相比，DnsForwarder配置特定DNS解析特定域名要更方便，而AcrylicDnsProxy规则配置略麻烦，但功能可能要更强一些，不过整体上两种组合都差不多，就看自己哪个更顺手了
