### ISSUE TITLE
DnsForwarderGUI 与v2ray   貌似有冲突

### ISSUE THREAD

**Issue by zengyu520** [miaomiaosoft/DnsForwarderGUI#3]
dnschooser软件内 一直安装不上  然后跑作者那边直接下载安装了     再DnsForwarderGUI里显示运行  然后 电脑上有开v2ray  貌似感觉有冲突。。   日志里面没动静  

AcrylicDnsProxy 之前安装这个 各种网络连不上。 用DnsForwarderGUI   这个倒是可以  但是感觉软件没起作用 （门外汉  只知道根教程来 v2ray也是一键配置在谷歌云上的）  求解。谢谢

**Comment by zengyu520** [comment]
DnsChooser  软件显示管理模式的  

DnsChooser 这个配置文件在叫什么呢  需要如何更改呢。          -----话说 你是白天吗  这大半夜的 哈哈

**Comment by miaomiaosoft** [comment]
DnsChooser的配置文件就在它程序目录下面 dnschooser.conf
最好还是在GUI里安装

**Comment by zengyu520** [comment]
DnsForwarder   配置文件  找到 这个 UDPGroup 1.2.4.8:53,114.114.114.114 * on     直接替换上面你说的UDPGroup 127.0.0.3:56 * on  就可以吧       

嗯  我先把单独的卸载试试看  然后用DnsForwarder  安装dnschooser 试试

**Comment by zengyu520** [comment]
单独安装的 DnsChooser  卸载了  

然后在重新下载了DnsForwarder
文件解压到根目录的DnsForwarder文件夹里了，包含（DnsChooser文件夹，Config.ini 运行后生成，dnsforwarder.config 直接下载，DnsForwarderGUI.exe 也是下载），然后我用管理员模式运行 DnsForwarderGUI.exe，点DnsChooser 安装运行 但是一直提示DnsChooser已经停止。。

**Comment by zengyu520** [comment]
电脑的DNS 我改成了127.0.0.1了

**Comment by miaomiaosoft** [comment]
那就换回单独安装dnschooser吧，只要配置按上面说的改了就行

**Comment by zengyu520** [comment]
嗯   配置对了下  把压缩包里的配置文件直接粘贴进去了     上面的命令都有了  应该没问题了  
https://github.com/holmium/dnsforwarder/blob/6/default.config 配置文件我给偷懒了 右键出来的都是乱码  我整个都复制进去  都正常了     就是不知道我这电脑有没走软件  谢谢了

**Comment by miaomiaosoft** [comment]
开日志啊 
LogFileFolder Z:\log
设定一个日志路径就可以了

或者随便加一个HOSTs 
127.0.0.1 qq.com
CMD下
nslookup qq.com
如果结果是127.0.0.1 那就在用了

**Comment by zengyu520** [comment]
日志开了。我对照你的路劲 LogFileFolder Z:\WINRAR    在客户端开了一个   
 LogFileFolder F:\DnsForwarder

hosts 加了 QQ   网页能打开  日志还是没动静  感觉更最新的win10 有点bug   打开的时候会卡半天  。。

**Comment by zengyu520** [comment]
单独安装的dnschooser  点安装没反应了。。。

**Comment by miaomiaosoft** [comment]
要么远程吧。。。这么搞我也弄不清你那什么情况
