### ISSUE TITLE
选项问题

### ISSUE THREAD

**Issue by sunnyday2006** [miaomiaosoft/DnsForwarderGUI#4]
如题：首次运行后，点击 “DnsChooser”选项卡 - “安装运行”，提示成功，并且在任务管理器看到 ‘dnsforwarder’和‘DnsForwarderGUI’有在运行。但是返回去看，“服务设定”仍显示DnsChooser已停止。这是设置没对，还是其它问题？

另，如果上面没错，以后GUI“选项”选项卡不打钩开机自启（GUI不需要启动），之前安装好的服务自启就可以实现正常运行是吗？

**Comment by miaomiaosoft** [comment]
没发现DnsChooser进程的话应该是没启动，DnsChooser的安装运行实际是安装成服务运行，应该需要管理员权限才行吧
如服务安装成功那以后的自启就不依赖DnsForwarderGUI

DnsForwarder进程的自启需要依赖DnsForwarderGUI
